import type { AutomationRule, NotificationEventType, NotificationChannel, NotificationAudience, NotificationPriority } from "@/types/notifications";

const automationRules: AutomationRule[] = [
  {
    id: "rule_daily_mission_available",
    name: "Daily mission available",
    eventType: "DailyMissionAvailable",
    description: "Notify employees when today's mission becomes available.",
    audience: ["EMPLOYEE"],
    channels: ["IN_APP", "EMAIL"],
    frequency: "once",
    enabled: true,
    mandatory: false,
    priority: "NORMAL",
  },
  {
    id: "rule_mission_missed",
    name: "Missed mission reminder",
    eventType: "MissionMissed",
    description: "Send a one-time reminder when a mission is overdue.",
    audience: ["EMPLOYEE"],
    channels: ["IN_APP", "EMAIL"],
    frequency: "once",
    enabled: true,
    mandatory: false,
    priority: "HIGH",
  },
  {
    id: "rule_employee_at_risk",
    name: "Employees falling behind",
    eventType: "EmployeeAtRisk",
    description: "Notify employees and managers when training risk becomes high.",
    audience: ["EMPLOYEE", "MANAGER"],
    channels: ["IN_APP", "EMAIL"],
    frequency: "once_per_risk_event",
    enabled: true,
    mandatory: true,
    priority: "CRITICAL",
  },
  {
    id: "rule_employee_back_on_track",
    name: "Back on track",
    eventType: "EmployeeBackOnTrack",
    description: "Notify employees when they return to required pace.",
    audience: ["EMPLOYEE"],
    channels: ["IN_APP"],
    frequency: "once",
    enabled: true,
    mandatory: false,
    priority: "NORMAL",
  },
  {
    id: "rule_campaign_deadline_approaching",
    name: "Campaign deadline approaching",
    eventType: "CampaignDeadlineApproaching",
    description: "Notify administrators when a campaign deadline is nearing.",
    audience: ["ADMIN", "HR"],
    channels: ["EMAIL"],
    frequency: "once",
    enabled: true,
    mandatory: false,
    priority: "HIGH",
  },
  {
    id: "rule_campaign_completed",
    name: "Campaign completed",
    eventType: "CampaignCompleted",
    description: "Notify administrators when a campaign completes.",
    audience: ["ADMIN", "HR"],
    channels: ["EMAIL"],
    frequency: "once",
    enabled: true,
    mandatory: false,
    priority: "NORMAL",
  },
  {
    id: "rule_certificate_issued",
    name: "Certificate issued",
    eventType: "CertificateIssued",
    description: "Notify employees when a certificate is issued.",
    audience: ["EMPLOYEE"],
    channels: ["IN_APP", "EMAIL"],
    frequency: "once",
    enabled: true,
    mandatory: false,
    priority: "NORMAL",
  },
  {
    id: "rule_certificate_expiring",
    name: "Certificate expiring",
    eventType: "CertificateExpiring",
    description: "Notify employees 30 days before certificate expiry.",
    audience: ["EMPLOYEE"],
    channels: ["IN_APP", "EMAIL"],
    frequency: "once",
    enabled: true,
    mandatory: false,
    priority: "HIGH",
  },
  {
    id: "rule_weekly_compliance_summary",
    name: "Weekly compliance summary",
    eventType: "WeeklyComplianceSummary",
    description: "Send weekly compliance summaries to administrators.",
    audience: ["ADMIN", "HR"],
    channels: ["EMAIL"],
    frequency: "weekly",
    enabled: true,
    mandatory: false,
    priority: "LOW",
  },
];

export function getAutomationRules(): AutomationRule[] {
  return automationRules;
}

export function getAutomationRuleByEvent(eventType: NotificationEventType): AutomationRule | undefined {
  return automationRules.find((rule) => rule.eventType === eventType);
}
