import type { EmployeeFiltersState, EmployeeRecord } from "@/types/employee-management";

export const employeeFiltersDefaults: EmployeeFiltersState = {
  department: "All",
  location: "All",
  manager: "All",
  campaign: "All",
  complianceStatus: "All",
};

export const mockEmployees: EmployeeRecord[] = [
  {
    id: "emp-001",
    name: "Ava Johnson",
    employeeNumber: "EMP001",
    department: "Operations",
    manager: "Nadia Brooks",
    location: "Johannesburg",
    campaign: "Fire Safety Refresh",
    progress: 72,
    lessonsCompleted: 18,
    totalLessons: 25,
    complianceScore: 92,
    status: "In Progress",
    lastActivity: "2 hours ago",
    xp: 1840,
    level: 12,
    quizAverage: 86,
    scenarioCompletion: 71,
    timeRemaining: "3 days",
    certificates: [
      { title: "PPE Awareness", expiryDate: "Jan 2027", status: "Valid" },
      { title: "Incident Response", expiryDate: "Feb 2027", status: "Valid" },
    ],
    activityTimeline: [
      { title: "Completed Lesson", meta: "Emergency Response Basics" },
      { title: "Passed Quiz", meta: "Fire Drill Assessment" },
      { title: "Reminder Sent", meta: "Sent 1 day ago" },
    ],
    aiInsight: "Employee has missed two learning days. Completion probability is 78%. A reminder today is recommended.",
  },
  {
    id: "emp-002",
    name: "Liam Patel",
    employeeNumber: "EMP002",
    department: "Engineering",
    manager: "Rafael Gomez",
    location: "Cape Town",
    campaign: "Equipment Safety",
    progress: 54,
    lessonsCompleted: 13,
    totalLessons: 24,
    complianceScore: 81,
    status: "In Progress",
    lastActivity: "Yesterday",
    xp: 1520,
    level: 10,
    quizAverage: 79,
    scenarioCompletion: 58,
    timeRemaining: "5 days",
    certificates: [{ title: "Lockout Tagout", expiryDate: "Mar 2027", status: "Valid" }],
    activityTimeline: [
      { title: "Completed Lesson", meta: "Hazard Reporting" },
      { title: "Finished Scenario", meta: "Blocked Exit" },
    ],
    aiInsight: "Completion probability is 68%. Manager follow-up is recommended this week.",
  },
  {
    id: "emp-003",
    name: "Sarah Mokoena",
    employeeNumber: "EMP003",
    department: "Warehouse",
    manager: "Darren Cole",
    location: "Durban",
    campaign: "Warehouse Safety",
    progress: 100,
    lessonsCompleted: 20,
    totalLessons: 20,
    complianceScore: 96,
    status: "Compliant",
    lastActivity: "Today",
    xp: 2200,
    level: 14,
    quizAverage: 95,
    scenarioCompletion: 100,
    timeRemaining: "Completed",
    certificates: [{ title: "Warehouse Safety", expiryDate: "Apr 2027", status: "Valid" }],
    activityTimeline: [
      { title: "Certificate Earned", meta: "Warehouse Safety" },
      { title: "Passed Quiz", meta: "Critical Hazards" },
    ],
    aiInsight: "Fully compliant and ahead of the expected completion pace.",
  },
  {
    id: "emp-004",
    name: "Noah Mbatha",
    employeeNumber: "EMP004",
    department: "Construction",
    manager: "Tendai Moyo",
    location: "Gqeberha",
    campaign: "Site Safety",
    progress: 18,
    lessonsCompleted: 4,
    totalLessons: 22,
    complianceScore: 47,
    status: "Overdue",
    lastActivity: "5 days ago",
    xp: 590,
    level: 6,
    quizAverage: 56,
    scenarioCompletion: 22,
    timeRemaining: "1 day",
    certificates: [],
    activityTimeline: [{ title: "Reminder Sent", meta: "Sent 3 days ago" }],
    aiInsight: "Employee is at high risk of missing the deadline and should receive immediate intervention.",
  },
  {
    id: "emp-005",
    name: "Priya Singh",
    employeeNumber: "EMP005",
    department: "HR",
    manager: "Mina Lewis",
    location: "Pretoria",
    campaign: "Policy Awareness",
    progress: 0,
    lessonsCompleted: 0,
    totalLessons: 16,
    complianceScore: 0,
    status: "Not Started",
    lastActivity: "2 weeks ago",
    xp: 0,
    level: 1,
    quizAverage: 0,
    scenarioCompletion: 0,
    timeRemaining: "7 days",
    certificates: [],
    activityTimeline: [{ title: "Reminder Sent", meta: "Scheduled for tomorrow" }],
    aiInsight: "No engagement has been recorded yet. A welcome reminder may improve early completion.",
  },
];
